/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
  'radius' : IDL.Float64,
});
export const DashboardStats = IDL.Record({
  'totalTasks' : IDL.Nat,
  'totalPlatformFees' : IDL.Float64,
  'completedTasks' : IDL.Nat,
  'activeWorkers' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
});
export const PushNotification = IDL.Record({
  'id' : IDL.Nat,
  'workerId' : IDL.Principal,
  'taskDetails' : IDL.Text,
  'isRead' : IDL.Bool,
  'taskId' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const AiAgentClientProfile = IDL.Record({
  'principal' : IDL.Principal,
  'createdAt' : IDL.Int,
  'agentName' : IDL.Text,
  'description' : IDL.Text,
});
export const Skill = IDL.Variant({
  'custom' : IDL.Text,
  'arCaptures' : IDL.Null,
  'delivery' : IDL.Null,
  'verification' : IDL.Null,
  'photography' : IDL.Null,
});
export const HumanWorkerProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'available' : IDL.Bool,
  'rating' : IDL.Float64,
  'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'price' : IDL.Float64,
  'skills' : IDL.Vec(Skill),
  'location' : Location,
});
export const UserProfile = IDL.Record({
  'aiAgent' : IDL.Opt(AiAgentClientProfile),
  'humanWorker' : IDL.Opt(HumanWorkerProfile),
  'profileType' : IDL.Variant({
    'aiAgent' : IDL.Null,
    'humanWorker' : IDL.Null,
  }),
});
export const DailyStats = IDL.Record({
  'date' : IDL.Int,
  'totalFees' : IDL.Float64,
  'taskCount' : IDL.Nat,
});
export const DailySummary = IDL.Record({
  'day' : IDL.Int,
  'completedAmount' : IDL.Float64,
  'completedTasks' : IDL.Nat,
  'taskCount' : IDL.Nat,
  'totalAmount' : IDL.Float64,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptTask' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculatePlatformFees' : IDL.Func([], [IDL.Float64], ['query']),
  'completeTaskPayment' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, Location],
      [IDL.Nat],
      [],
    ),
  'getAdminDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(PushNotification)], ['query']),
  'getAllUserIds' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAndUpdateCurrentPrice' : IDL.Func(
      [],
      [IDL.Record({ 'currency' : IDL.Opt(IDL.Text), 'price' : IDL.Float64 })],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyEarningsStats' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(DailyStats)],
      ['query'],
    ),
  'getDailySummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'day' : IDL.Int,
          'completedAmount' : IDL.Float64,
          'completedTasks' : IDL.Nat,
          'taskCount' : IDL.Nat,
          'totalAmount' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getLast7DaysStats' : IDL.Func([], [IDL.Vec(DailySummary)], ['query']),
  'getPlatformFeeTotal' : IDL.Func([], [IDL.Float64], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTodayAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'day' : IDL.Int,
          'totalEarnings' : IDL.Float64,
          'acceptedTasks' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUnreadNotifications' : IDL.Func(
      [],
      [IDL.Vec(PushNotification)],
      ['query'],
    ),
  'getUnreadNotificationsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'registerAiAgent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerHumanWorker' : IDL.Func(
      [IDL.Text, IDL.Vec(Skill), Location, IDL.Float64],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'search' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Float64, IDL.Float64],
      [IDL.Vec(HumanWorkerProfile)],
      ['query'],
    ),
  'setPlatformFeeWallet' : IDL.Func([IDL.Principal], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateHumanWorkerProfile' : IDL.Func(
      [IDL.Text, IDL.Vec(Skill), Location, IDL.Float64],
      [],
      [],
    ),
  'uploadProfilePicture' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Location = IDL.Record({
    'lat' : IDL.Float64,
    'lon' : IDL.Float64,
    'radius' : IDL.Float64,
  });
  const DashboardStats = IDL.Record({
    'totalTasks' : IDL.Nat,
    'totalPlatformFees' : IDL.Float64,
    'completedTasks' : IDL.Nat,
    'activeWorkers' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
  });
  const PushNotification = IDL.Record({
    'id' : IDL.Nat,
    'workerId' : IDL.Principal,
    'taskDetails' : IDL.Text,
    'isRead' : IDL.Bool,
    'taskId' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const AiAgentClientProfile = IDL.Record({
    'principal' : IDL.Principal,
    'createdAt' : IDL.Int,
    'agentName' : IDL.Text,
    'description' : IDL.Text,
  });
  const Skill = IDL.Variant({
    'custom' : IDL.Text,
    'arCaptures' : IDL.Null,
    'delivery' : IDL.Null,
    'verification' : IDL.Null,
    'photography' : IDL.Null,
  });
  const HumanWorkerProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'available' : IDL.Bool,
    'rating' : IDL.Float64,
    'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'price' : IDL.Float64,
    'skills' : IDL.Vec(Skill),
    'location' : Location,
  });
  const UserProfile = IDL.Record({
    'aiAgent' : IDL.Opt(AiAgentClientProfile),
    'humanWorker' : IDL.Opt(HumanWorkerProfile),
    'profileType' : IDL.Variant({
      'aiAgent' : IDL.Null,
      'humanWorker' : IDL.Null,
    }),
  });
  const DailyStats = IDL.Record({
    'date' : IDL.Int,
    'totalFees' : IDL.Float64,
    'taskCount' : IDL.Nat,
  });
  const DailySummary = IDL.Record({
    'day' : IDL.Int,
    'completedAmount' : IDL.Float64,
    'completedTasks' : IDL.Nat,
    'taskCount' : IDL.Nat,
    'totalAmount' : IDL.Float64,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptTask' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculatePlatformFees' : IDL.Func([], [IDL.Float64], ['query']),
    'completeTaskPayment' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, Location],
        [IDL.Nat],
        [],
      ),
    'getAdminDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getAllNotifications' : IDL.Func(
        [],
        [IDL.Vec(PushNotification)],
        ['query'],
      ),
    'getAllUserIds' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAndUpdateCurrentPrice' : IDL.Func(
        [],
        [IDL.Record({ 'currency' : IDL.Opt(IDL.Text), 'price' : IDL.Float64 })],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyEarningsStats' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(DailyStats)],
        ['query'],
      ),
    'getDailySummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'day' : IDL.Int,
            'completedAmount' : IDL.Float64,
            'completedTasks' : IDL.Nat,
            'taskCount' : IDL.Nat,
            'totalAmount' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getLast7DaysStats' : IDL.Func([], [IDL.Vec(DailySummary)], ['query']),
    'getPlatformFeeTotal' : IDL.Func([], [IDL.Float64], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTodayAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'day' : IDL.Int,
            'totalEarnings' : IDL.Float64,
            'acceptedTasks' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUnreadNotifications' : IDL.Func(
        [],
        [IDL.Vec(PushNotification)],
        ['query'],
      ),
    'getUnreadNotificationsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'registerAiAgent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerHumanWorker' : IDL.Func(
        [IDL.Text, IDL.Vec(Skill), Location, IDL.Float64],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'search' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Float64, IDL.Float64],
        [IDL.Vec(HumanWorkerProfile)],
        ['query'],
      ),
    'setPlatformFeeWallet' : IDL.Func([IDL.Principal], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateHumanWorkerProfile' : IDL.Func(
        [IDL.Text, IDL.Vec(Skill), Location, IDL.Float64],
        [],
        [],
      ),
    'uploadProfilePicture' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };