/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiAgentClientProfile {
  'principal' : Principal,
  'createdAt' : bigint,
  'agentName' : string,
  'description' : string,
}
export interface DailyStats {
  'date' : bigint,
  'totalFees' : number,
  'taskCount' : bigint,
}
export interface DailySummary {
  'day' : bigint,
  'completedAmount' : number,
  'completedTasks' : bigint,
  'taskCount' : bigint,
  'totalAmount' : number,
}
export interface DashboardStats {
  'totalTasks' : bigint,
  'totalPlatformFees' : number,
  'completedTasks' : bigint,
  'activeWorkers' : bigint,
  'totalRevenue' : number,
}
export interface HumanWorkerProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'available' : boolean,
  'rating' : number,
  'photo' : [] | [Uint8Array],
  'price' : number,
  'skills' : Array<Skill>,
  'location' : Location,
}
export interface Location { 'lat' : number, 'lon' : number, 'radius' : number }
export interface PushNotification {
  'id' : bigint,
  'workerId' : Principal,
  'taskDetails' : string,
  'isRead' : boolean,
  'taskId' : bigint,
  'timestamp' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type Skill = { 'custom' : string } |
  { 'arCaptures' : null } |
  { 'delivery' : null } |
  { 'verification' : null } |
  { 'photography' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'aiAgent' : [] | [AiAgentClientProfile],
  'humanWorker' : [] | [HumanWorkerProfile],
  'profileType' : { 'aiAgent' : null } |
    { 'humanWorker' : null },
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptTask' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculatePlatformFees' : ActorMethod<[], number>,
  'completeTaskPayment' : ActorMethod<[bigint, number], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createTask' : ActorMethod<
    [string, string, string, number, Location],
    bigint
  >,
  'getAdminDashboardStats' : ActorMethod<[], DashboardStats>,
  'getAllNotifications' : ActorMethod<[], Array<PushNotification>>,
  'getAndUpdateCurrentPrice' : ActorMethod<
    [],
    { 'currency' : [] | [string], 'price' : number }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyEarningsStats' : ActorMethod<[bigint, bigint], Array<DailyStats>>,
  'getDailySummary' : ActorMethod<
    [],
    {
      'day' : bigint,
      'completedAmount' : number,
      'completedTasks' : bigint,
      'taskCount' : bigint,
      'totalAmount' : number,
    }
  >,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getLast7DaysStats' : ActorMethod<[], Array<DailySummary>>,
  'getPlatformFeeTotal' : ActorMethod<[], number>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTodayAdminStats' : ActorMethod<
    [],
    { 'day' : bigint, 'totalEarnings' : number, 'acceptedTasks' : bigint }
  >,
  'getUnreadNotifications' : ActorMethod<[], Array<PushNotification>>,
  'getUnreadNotificationsCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'registerAiAgent' : ActorMethod<[string, string], undefined>,
  'registerHumanWorker' : ActorMethod<
    [string, Array<Skill>, Location, number],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'search' : ActorMethod<
    [Array<string>, number, number],
    Array<HumanWorkerProfile>
  >,
  'setPlatformFeeWallet' : ActorMethod<[Principal], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateHumanWorkerProfile' : ActorMethod<
    [string, Array<Skill>, Location, number],
    undefined
  >,
  'uploadProfilePicture' : ActorMethod<[Uint8Array], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];